{{- if not (.Values.secret).existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-logger.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "discord-logger.name" . }}
    helm.sh/chart: {{ include "discord-logger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  secrets: |-
    TOKEN = '{{ (.Values.secret).token }}'
    MONGO_URI = '{{ (.Values.secret).mongoUri }}'
{{- end }}