apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord-logger.fullname" . }}-settings
  labels:
    app.kubernetes.io/name: {{ include "discord-logger.name" . }}
    helm.sh/chart: {{ include "discord-logger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  settings: |-
    {{- .Values.settings | nindent 4 }}
