name: Verify Chart Release Versions

on:
  pull_request:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        id: install
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          rm -rf get_helm.sh

      - name: Verify Chart Release Versions
        run: |
          for chart in charts/*; do
            diff=$(git --no-pager diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} "$chart")
            helm_version=$(helm show chart "$chart" | yq '.version' -)
            if [[ -n $diff ]] && [[ ! $(echo $diff | grep "version: $version") ]]; then
              echo "Chart $(helm show chart "$chart" | yq '.name' -) has not been updated to a newer version."
              echo "Current version: $helm_version"
              echo "Please update the chart version to a newer version before merging."
              fail=true
            fi
            if [[ $fail == true ]]; then
              exit 1
            fi
          done